name = "life-app-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "../public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "life-app-db"
database_id = "ee0d526f-3a06-4785-b3e8-840ab9db3a09"
migrations_dir = "migrations"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
